// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VailInstructorWikiApi;

#nullable disable

namespace VailInstructorWikiApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230603155616_InstructorDb4")]
    partial class InstructorDb4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VailInstructorWikiApi.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Area", (string)null);
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Drill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Discipline")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drill", (string)null);
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discpline")
                        .HasColumnType("int");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Level", (string)null);
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrailRating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Run", (string)null);
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.RunDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discipline")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int>("RunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("RunId");

                    b.ToTable("RunDiscipline", (string)null);
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.RunDisciplineDrill", b =>
                {
                    b.Property<int>("RunDisciplineId")
                        .HasColumnType("int");

                    b.Property<int>("DrillId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("RunDisciplineId", "DrillId");

                    b.HasIndex("DrillId");

                    b.ToTable("RunDisciplineDrill", (string)null);
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discpline")
                        .HasColumnType("int");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Run", b =>
                {
                    b.HasOne("VailInstructorWikiApi.Models.Area", "Area")
                        .WithMany("Runs")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.RunDiscipline", b =>
                {
                    b.HasOne("VailInstructorWikiApi.Models.Level", "Level")
                        .WithMany("RunDisciplines")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VailInstructorWikiApi.Models.Run", "Run")
                        .WithMany("RunDisciplines")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.RunDisciplineDrill", b =>
                {
                    b.HasOne("VailInstructorWikiApi.Models.Drill", "Drill")
                        .WithMany("RunDisciplineDrills")
                        .HasForeignKey("DrillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VailInstructorWikiApi.Models.RunDiscipline", "RunDiscipline")
                        .WithMany("RunDisciplineDrills")
                        .HasForeignKey("RunDisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drill");

                    b.Navigation("RunDiscipline");
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Skill", b =>
                {
                    b.HasOne("VailInstructorWikiApi.Models.Level", "Level")
                        .WithMany("Skills")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Area", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Drill", b =>
                {
                    b.Navigation("RunDisciplineDrills");
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Level", b =>
                {
                    b.Navigation("RunDisciplines");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.Run", b =>
                {
                    b.Navigation("RunDisciplines");
                });

            modelBuilder.Entity("VailInstructorWikiApi.Models.RunDiscipline", b =>
                {
                    b.Navigation("RunDisciplineDrills");
                });
#pragma warning restore 612, 618
        }
    }
}
